In [11]:
## **AI-Powered Personalized Learning Recommendation System**

In [24]:
### Features
#- Skill Gap Analysis
#- Interest-Based Recommendation
#- Goal-Based Recommendation
#- Adaptive Learning Roadmap
#- Learning Style Recommendation

### Dataset
#Coursera Courses and Skills Dataset 2025

In [12]:
## Import libraries

In [3]:
import pandas as pd
import numpy as np

In [13]:
## Upload dataset and read

In [5]:
df = pd.read_csv("/content/Coursera.csv")
df

,Subject,Title,Institution,Learning Product,Level,Duration,Gained Skills,Rate,Reviews
0,Business,Business Analysis & Process Management,Coursera Project Network,Guided Project,Beginner,Less Than 2 Hours,"Process Analysis, Business Process, Business A...",4.4,6100
1,Business,Getting Started with Microsoft Excel,Coursera Project Network,Guided Project,Intermediate,Less Than 2 Hours,"Microsoft Excel, Excel Formulas, Spreadsheet S...",4.6,11000
2,Business,Financial Markets,Yale University,Course,Beginner,1 - 3 Months,"Investment Banking, Risk Management, Financial...",4.8,30000
3,Business,Investment Risk Management,Coursera Project Network,Guided Project,Intermediate,Less Than 2 Hours,"Investment Management, Risk Management, Financ...",4.4,1800
4,Business,Food & Beverage Management,Università Bocconi,Course,Mixed,1 - 3 Months,"Food and Beverage, Hospitality, Restaurant Man...",4.8,4800
...,...,...,...,...,...,...,...,...,...
3399,Information Technology,Python Data Products for Predictive Analytics,University of California San Diego,Specialization,Intermediate,3 - 6 Months,"Supervised Learning, Feature Engineering, Pred...",4.6,14
3400,Information Technology,Basic Data Processing and Visualization,University of California San Diego,Course,Intermediate,1 - 3 Months,"Data Processing, Data Manipulation, Interactiv...",4.3,46
3401,Information Technology,Machine Learning: Concepts and Applications,The University of Chicago,Course,Intermediate,1 - 3 Months,"Keras (Neural Network Library), Unsupervised L...",4.6,66
3402,Information Technology,"Random Models, Nested and Split-plot Designs",Arizona State University,Course,Intermediate,1 - 4 Weeks,"Statistical Analysis, Regression Analysis, Sam...",4.1,12
3403,Information Technology,Finalize a Data Science Project,CertNexus,Course,Intermediate,1 - 4 Weeks,"Applied Machine Learning, Machine Learning, St...",4.8,6

In [14]:
## Check columns

In [6]:
df.columns

Index(['Subject', 'Title', 'Institution', 'Learning Product', 'Level',
       'Duration', 'Gained Skills', 'Rate', 'Reviews'],
      dtype='object')

In [7]:
df.head()

,Subject,Title,Institution,Learning Product,Level,Duration,Gained Skills,Rate,Reviews
0,Business,Business Analysis & Process Management,Coursera Project Network,Guided Project,Beginner,Less Than 2 Hours,"Process Analysis, Business Process, Business A...",4.4,6100
1,Business,Getting Started with Microsoft Excel,Coursera Project Network,Guided Project,Intermediate,Less Than 2 Hours,"Microsoft Excel, Excel Formulas, Spreadsheet S...",4.6,11000
2,Business,Financial Markets,Yale University,Course,Beginner,1 - 3 Months,"Investment Banking, Risk Management, Financial...",4.8,30000
3,Business,Investment Risk Management,Coursera Project Network,Guided Project,Intermediate,Less Than 2 Hours,"Investment Management, Risk Management, Financ...",4.4,1800
4,Business,Food & Beverage Management,Università Bocconi,Course,Mixed,1 - 3 Months,"Food and Beverage, Hospitality, Restaurant Man...",4.8,4800

In [8]:
df.isnull().sum()

Subject             0
Title               0
Institution         0
Learning Product    0
Level               0
Duration            0
Gained Skills       0
Rate                0
Reviews             0
dtype: int64

In [15]:
## User Profile

In [25]:
current_skills = ["Python","SQL"]

interest = "Artificial Intelligence"

goal = "Machine Learning Engineer"

difficulty = "Beginner"

study_time = 1

learning_style = "Video"

In [17]:
## Career Skills Dictionary

In [26]:
career_skills = {

"Machine Learning Engineer":
["Python","SQL","Statistics","Machine Learning","Deep Learning"],

"Data Scientist":
["Python","SQL","Statistics","Machine Learning","Power BI"],

"Data Analyst":
["Excel","SQL","Python","Power BI"]

}

In [19]:
## Skill Gap Analysis

In [27]:
required_skills = career_skills[goal]

missing_skills = list(set(required_skills)-set(current_skills))

print("Missing Skills")

print(missing_skills)

Missing Skills
['Statistics', 'Machine Learning', 'Deep Learning']

In [29]:
## Course Recommendation

In [28]:
print("Recommended Courses")

for skill in missing_skills:

    courses = df[
        df['Gained Skills'].str.contains(
            skill,
            case=False,
            na=False
        )
    ]

    print("\nSkill:", skill)

    if len(courses) > 0:
        print(courses['Title'].head(3).to_string(index=False))
    else:
        print("No course found")

Recommended Courses

Skill: Statistics
                          Behavioral Finance
Python and Statistics for Financial Analysis
          Foundations of Marketing Analytics

Skill: Machine Learning
                                   AI For Everyone
Generative AI for Human Resources (HR) Professi...
                     Key Technologies for Business

Skill: Deep Learning
                                   AI For Everyone
Generative AI for Human Resources (HR) Professi...
                     Key Technologies for Business

In [30]:
## Difficulty Level Personalization

In [31]:
print("Difficulty Level")

print(difficulty)

Difficulty Level
Beginner

In [32]:
## Study Time Based Roadmap

In [33]:
print("Learning Roadmap")

month = 1

for skill in missing_skills:

    print("Month",month,"→",skill)

    month += 1

Learning Roadmap
Month 1 → Statistics
Month 2 → Machine Learning
Month 3 → Deep Learning

In [ ]:
## Learning Style Recommendation

In [34]:
if learning_style == "Video":

    platforms = [
        "Coursera",
        "Udemy",
        "YouTube"
    ]

else:

    platforms = [
        "Books",
        "Documentation",
        "edX"
    ]

print("Recommended Platforms")

for i in platforms:

    print(i)

Recommended Platforms
Coursera
Udemy
YouTube

In [35]:
## Top Rated Courses

In [39]:
top_courses = df.sort_values(by=['Rate','Reviews'], ascending=[False,False])

print("Top Rated Courses\n")

print(top_courses[['Title','Institution','Rate','Reviews']].head(5).to_string(index=False))

Top Rated Courses

                                                   Title              Institution  Rate  Reviews
     Data Analysis and Reporting in SAS Visual Analytics                      SAS   5.0       34
  Responsible AI - Principles and Ethical Considerations        Fractal Analytics   5.0       30
        Free Trade Agreements and Special Economic Zones                PwC India   5.0       24
Excel for Beginners: Sorting, Filtering, Data-Validation Coursera Project Network   5.0       24
                               Consulting Tools and Tips         Emory University   5.0       23